all:
	mscgen -T png -o diagram_initialisation.png diagram_initialisation.msc
	mscgen -T png -o diagram_jeu.png diagram_jeu.msc
	mscgen -T png -o diagram_message.png diagram_message.msc
	mscgen -T png -o diagram_pingpong.png diagram_pingpong.msc
